GDPR/Pages/Consent.cshtml.cs
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GDPR.Pages
{
    public class Consent : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnPostGrantAsync()
        {
            HttpContext.Features.Get<ITrackingConsentFeature>().GrantConsent();
            return RedirectToPage("./Index");
        }

        public IActionResult OnPostWithdrawAsync()
        {
            HttpContext.Features.Get<ITrackingConsentFeature>().WithdrawConsent();
            return RedirectToPage("./Index");
        }
    }
}

GDPR/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GDPR.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

GDPR/Pages/Cookie.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Net.Http.Headers;
using System;

namespace GDPR.Pages
{
    public class Cookie : PageModel
    {
        [TempData]
        public string ResponseCookies { get; set; }

        public void OnGet()
        {
        }

        #region snippet1
        public IActionResult OnPostCreateEssentialAsync()
        {
            HttpContext.Response.Cookies.Append(Constants.EssentialSec, 
                DateTime.Now.Second.ToString(), 
                new CookieOptions() { IsEssential = true });

            ResponseCookies = Response.Headers[HeaderNames.SetCookie].ToString();

            return RedirectToPage("./Index");
        }
        #endregion

        public IActionResult OnPostCreateAsync()
        {
            HttpContext.Response.Cookies.Append(Constants.NonEssentialMS, 
                DateTime.Now.Millisecond.ToString());

            ResponseCookies = Response.Headers[HeaderNames.SetCookie].ToString();

            return RedirectToPage("./Index");
        }

        public IActionResult OnPostDeleteAsync()
        {
            HttpContext.Response.Cookies.Delete(Constants.NonEssentialMS);
            HttpContext.Response.Cookies.Delete(Constants.EssentialSec);

            return RedirectToPage("./Index");
        }

        public IActionResult OnPostDeleteAllAsync()
        {

            foreach (var cookie in Request.Cookies.Keys)
            {
                Response.Cookies.Delete(cookie);
            }

            return RedirectToPage("./Index");
        }
    }
}

GDPR/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GDPR.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

GDPR/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GDPR.Pages
{
    public class IndexModel : PageModel
    {
        public ITrackingConsentFeature TrackingConsentFeature;
        public IRequestCookieCollection RequestCookieCollection;

        [TempData]
        public string ResponseCookies { get; set; }

        public void OnGet()
        {
            RequestCookieCollection = Request.Cookies;
            TrackingConsentFeature = HttpContext.Features.Get<ITrackingConsentFeature>();
        }
    }
}

GDPR/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GDPR.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

GDPR/Pages/Consent.cshtml
@page
@model Consent
@{
    ViewData["Title"] = "Consent";
}
<h2>@ViewData["Title"]</h2>

<form method="post">

    <div class="form-group">
        <input type="submit" value="Grant" asp-page-handler="Grant" class="btn btn-default" />
    </div>

    <div class="form-group">
        <input type="submit" value="Withdraw" asp-page-handler="Withdraw" class="btn btn-default" />
    </div>
</form>

GDPR/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GDPR/Pages/Cookie.cshtml
@page
@model Cookie
@{
    ViewData["Title"] = "Cookie";
}
<h2>@ViewData["Title"]</h2>

<form method="post">

    <div class="form-group">
        <input type="submit" value="Create non-essential" asp-page-handler="Create" class="btn btn-default" />
    </div>

    <div class="form-group">
        <input type="submit" value="Create essential" asp-page-handler="CreateEssential" class="btn btn-default" />
    </div>

    <div class="form-group">
        <input type="submit" value="Delete Non-essential and essential" asp-page-handler="Delete" class="btn btn-default" />
    </div>

    <div class="form-group">
        <input type="submit" value="Delete All" asp-page-handler="DeleteAll" class="btn btn-default" />
    </div>
</form>

GDPR/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h2> Home Page</h2>

    Consent:
<ul>
    <li>IsNeeded: @Model.TrackingConsentFeature.IsConsentNeeded</li>
    <li>Has: @Model.TrackingConsentFeature.HasConsent</li>
    <li>Can track: @Model.TrackingConsentFeature.CanTrack</li>

</ul>

<h3>Non Antiforgery request cookies</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                Key
            </th>
            <th>
                Value
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.RequestCookieCollection)
        {
            if (!item.Key.Contains("Antiforgery"))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Key)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Value)
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<h3>Response cookies </h3>

 @Model.ResponseCookies

GDPR/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GDPR</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">GDPR</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/Cookie">Cookie</a></li>
                    <li><a asp-page="/Consent">Consent</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - GDPR</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>